#*Image* cv2

In [ ]:
#!pip install opencv-python

In [88]:
import cv2

In [89]:
path='___.png'

In [90]:
img=cv2.imread(path,1) 

''' 0 denotes grayscale image
    1 denotes colored image
    -1 denotes no change in image'''

' 0 denotes grayscale image\n    1 denotes colored image\n    -1 denotes no change in image'

In [91]:
print(img.shape) # (Rows,Columns,Channels)
print(img) 

(543, 820, 3)
[[[248 248 248]
  [247 247 247]
  [247 247 247]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]

 [[247 247 247]
  [246 246 246]
  [246 246 246]
  ...
  [246 246 246]
  [246 246 246]
  [247 247 247]]

 [[247 247 247]
  [246 246 246]
  [246 246 246]
  ...
  [246 246 246]
  [246 246 246]
  [247 247 247]]

 ...

 [[247 247 247]
  [246 246 246]
  [246 246 246]
  ...
  [246 246 246]
  [246 246 246]
  [247 247 247]]

 [[246 246 246]
  [246 246 246]
  [246 246 246]
  ...
  [246 246 246]
  [246 246 246]
  [247 247 247]]

 [[248 247 249]
  [247 246 248]
  [247 246 248]
  ...
  [247 247 247]
  [247 247 247]
  [247 247 247]]]


In [92]:
cv2.imshow('image',img) # show the image in 'image' window
cv2.waitKey(0) 
cv2.destroyAllWindows()


In [93]:
cv2.imshow('image',img)
k=cv2.waitKey(0) 

''' displays until one of the conditions are met since wait key is 0 otherwise displays for given duration'''

if k==27:
    cv2.destroyAllWindows() # if Esc key is pressed it destroys all the windows 
elif k==ord('c'):
    cv2.imwrite('shrek_copy.png',img) # if c is pressed it makes a copy of the image 
    cv2.destroyAllWindows()

In [94]:
#Generating a blank image using numpy

import numpy as np
img_blank=np.zeros((128,128,3),dtype='uint8')
cv2.imshow('black',img_blank)
cv2.waitKey(0) 
cv2.destroyAllWindows()
cv2.imwrite('black_1.png',img_blank)

True

DRAWING_FUNCTIONS

In [95]:
img=cv2.line(img,(0,0),(10,300),(50,230,255),6)
cv2.imshow('image_line',img)
cv2.waitKey(0) 
cv2.destroyAllWindows()
cv2.imwrite('img_2.png',img)

True

In [96]:
img_blank=cv2.circle(img_blank,(64,64),20,(0,100,255),-1)
cv2.imshow('black_c',img_blank)
cv2.waitKey(0) 
cv2.destroyAllWindows()
cv2.imwrite('black_2.png',img_blank)

True

In [97]:
font=cv2.FONT_HERSHEY_SIMPLEX
img=cv2.imread(path,0)
img=cv2.putText(img,'Hi, I am Shrek',(20,100),font,2,(0,0,255),5,cv2.LINE_AA)
cv2.imshow('image_text',img)
cv2.waitKey(0) 
cv2.destroyAllWindows()
cv2.imwrite('img_3.png',img)

True

In [98]:
'''circular edge on image'''
'''Equation of the circle => (x – h)2 + (y – k)2 = r2
   Here centre is at origin so (h,k)=(0,0)
   Therefore r=sqrt((x)2 + (y)2) '''

img_blank=np.zeros((128,128,3),dtype='uint8')
#cv2.imshow('black',img_blank)

(centerY, centerX) = (img_blank.shape[0]//2, img_blank.shape[1]//2)

# draw a circular edge around picture
# set color at edge to white
color = (255, 255, 255)  # white
radius = round((centerY**2 + centerX ** 2) ** 0.5)  # radius from center to origin
thickness = 25
cv2.circle(img_blank, (centerX, centerY), radius, color, thickness)
# display image
cv2.imshow('black_ce',img_blank)
cv2.waitKey(0) 
cv2.destroyAllWindows()
cv2.imwrite('black_3.png',img_blank)

True

In [99]:
img=cv2.imread(path,1)
for r in range (10,200,10):
   
   img=cv2.circle(img,(390,264),r,(0,100,255),2,cv2.LINE_8)

cv2.imshow('image_cc',img)
cv2.waitKey(0) 
cv2.destroyAllWindows()
cv2.imwrite('img_3.png',img)

True

In [100]:

img_blank=np.zeros((512,512,3),dtype='uint8')
for r in range (1,1000):
    rad=np.random.randint(1,5)
    cenX=np.random.randint(0,500)
    cenY=np.random.randint(0,300)
    color = (np.random.randint(0,256),np.random.randint(0,200),np.random.randint(0,250))
    img_blank=cv2.circle(img_blank,(cenX,cenY),rad,color,-1)
for n in range (1,150):
    rad=np.random.randint(10,100)
    cenX=np.random.randint(0,500)
    cenY=np.random.randint(300,500)
    color = (np.random.randint(0,250),np.random.randint(50,256),np.random.randint(100,200))
    img_blank=cv2.circle(img_blank,(cenX,cenY),rad,color,-1)
img_blank=cv2.putText(img_blank,'-priya_creations',(350,500),cv2.FONT_HERSHEY_SCRIPT_COMPLEX,0.7,(0,0,0),1,cv2.LINE_AA)
#cv2.imwrite('/content/drive/MyDrive/Colab Notebooks/CV2/img_gen.png',img_blank)
cv2.imshow('image_gen',img_blank)
cv2.waitKey(0) 
cv2.destroyAllWindows()
cv2.imwrite('black_4.png',img_blank)

True

MouseClickEvents

In [30]:
events=[i for i in dir(cv2) if 'EVENT' in i ] # print all events in dir
print(events)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [105]:
points=[]
def click_event (event,x,y,flags,param):
    if event==cv2.EVENT_LBUTTONDOWN: # print the coordinate x,y
        print(x,' ',y)
        cv2.putText(img,'('+str(x)+','+str(y)+')',(x,y),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0),2)
        cv2.imshow('co',img)
        cv2.imwrite('img_4.png',img)
    if event==cv2.EVENT_RBUTTONDOWN: # print BGR color of the coordinate x,y
        b=img[x,y,0]
        g=img[x,y,1]
        r=img[x,y,2]
        cv2.putText(img,str(b)+','+str(g)+','+str(r),(x,y),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0),2)
        cv2.imshow('co',img)
        cv2.imwrite('img_5.png',img)
        cimg=np.zeros((128,128,3),np.uint8)
        cimg[:] = [b,g,r]
        cv2.imshow('cimage',cimg)
        cv2.imwrite('img_6.png',cimg)
    if event==cv2.EVENT_RBUTTONDBLCLK:
        
        cv2.circle(img,(x,y),2,(255,245,150),-1)
        #print(points)
        points.append((x,y))
        #print(points)
        if len(points)>=2:
            cv2.line(img,points[-1],points[-2],(255,245,150),5)
            print(points[-1],points[-2])
            cv2.imshow('co',img) 
            cv2.imwrite('img_7.png',img)
img=cv2.imread(path,1)
cv2.imshow('image',img)

cv2.setMouseCallback('image',click_event)
cv2.waitKey(0)
cv2.destroyAllWindows


123   70
428   60
(509, 283) (283, 285)


<function destroyAllWindows>